### ISSUE TITLE
blank images in higher batch sizes 

### ISSUE THREAD

**Issue by nub2927** [ddPn08/Radiata#66] opened 2023-04-02 14:50 UTC
### Describe the bug

whenever i make an engine with batch size higher than 1 and try doing batch inferences i get one normal image and the rest are blank

### Reproduction

convert model into diffusers then convert it to engine and try running a batch of 4

### Expected behavior

all images from the batch be visible 

### System Info

windows 10 
installed via the diffult method since docker wouldn't work 
python 3.10
Build cuda_11.8.r11.8/compiler.31833905_0

### Validations

- [X] Read the [docs](https://ddPn08.github.io/Lsmith/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by jettan** [comment] 2023-04-12 02:57
I tried doing this too and here's what I've found: this seems to be caused by the clip batch size being fixed to 1. 
https://github.com/ddPn08/Lsmith/blob/main/modules/diffusion/tensorrt/clip.py#L17

Everywhere else the batch_size seems to take opts.args_size. 
You need to to rebuild the clip engine also using your preferred max_batch_size (e.g., 4, 8, 16...) , make sure to delete the models/openai folder first and rerun the application to force rebuilding clip.

Afterwards, you can change the max_batch_size as usual and rebuild your models which should now support different batch_sizes. (I wasn't able to load the model for batch_size=16 as it asks for 32GB of GPU memory, but 8 was no problem).

However, this would trigger a different bug where the prompts are not propagated to each part of the batch.

**Comment by ddPn08** [comment] 2023-04-30 23:14
Closing this issue as the project has been significantly updated. Please reopen if you still have problems.

**Closed by ddPn08** 2023-04-30 23:14 UTC
